name: 'athena_sandbox'
version: '1.0.0'
profile: 'athena_sandbox'

dbt-cloud:
  project-id: 517365
  defer-env-id: 486928

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  athena_sandbox:
    example:
      +materialized: view

seeds:
  athena_sandbox:
    +database: "{{ target.database }}"
    example:
      +enabled: true
